/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domino.vista;

import domino.control.ControlIG;
import domino.model.Fitxa;
import domino.model.Joc;
import domino.model.Jugador;
import java.awt.Dimension;
import java.util.ArrayDeque;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Eric
 */
public class InterficieGrafica extends javax.swing.JFrame {

    private final int WIDTH = 1240, HEIGHT = 570;
    private ControlIG control;
    private Jugador jug;
    private Joc joc;
    private String[] nomJugs;

    /**
     * Creates new form domino
     */
    public InterficieGrafica(ControlIG control) {
        initComponents();
        this.control = control;
        setBounds(0, 0, WIDTH, HEIGHT);
        setResizable(false);
        setLocationRelativeTo(null);
        setResizable(false);
        this.joc = control.getJoc();
    }

    /**
     * Metode que coloca el nom a cada jugador.
     */
    public void setJugNom() {
        nomJugs = new String[]{JOptionPane.showInputDialog(null, "Bienvenido! Introduce tu nombre"), "BOT1", "BOT2", "BOT3"};
        tfUser.setText(nomJugs[0]);
    }

    /**
     * Metode que seteja les imatges del jugador.
     */
    public void setImgFitxer() {
        JLabel[] posFichas = {fU1, fU2, fU3, fU4, fU5, fU6, fU7};
        for (int i = 0; i < 7; i++) {
            ImageIcon imagenFicha
                    = new ImageIcon(getClass().getResource("/domino/assets/usuario/" + joc.getJugadors()[0].getFitxes().get(i).toString() + ".png"));
            posFichas[i].setIcon(imagenFicha);
        }
    }

    /**
     * Metode per posar imatges de les fitxes al tauler.
     *
     * @param fitxa
     */
    public void setFitxasTauler(Fitxa fitxa) {
        System.out.println(fitxa + "je");
        int contador = 0;
        ImageIcon imagenFicha = new ImageIcon(getClass().getResource("/domino/assets/usuario/" + fitxa + ".png"));
        switch(contador){
            case 0:
                img1.setIcon(imagenFicha);
                        panelTauler.add(img1);//TODO
                break;
            case 1:
                img2.setIcon(imagenFicha);
                        panelTauler.add(img2);
                break;
        }
        contador++;
        panelTauler.add(img3);
        System.out.println("OLA");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        tfUser = new javax.swing.JTextField();
        fU7 = new javax.swing.JLabel();
        fU1 = new javax.swing.JLabel();
        fU2 = new javax.swing.JLabel();
        fU3 = new javax.swing.JLabel();
        fU4 = new javax.swing.JLabel();
        fU5 = new javax.swing.JLabel();
        fU6 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        tfBot1 = new javax.swing.JTextField();
        fB17 = new javax.swing.JLabel();
        fB11 = new javax.swing.JLabel();
        fB12 = new javax.swing.JLabel();
        fB13 = new javax.swing.JLabel();
        fB14 = new javax.swing.JLabel();
        fB15 = new javax.swing.JLabel();
        fB16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        tfBot2 = new javax.swing.JTextField();
        fB27 = new javax.swing.JLabel();
        fB21 = new javax.swing.JLabel();
        fB22 = new javax.swing.JLabel();
        fB23 = new javax.swing.JLabel();
        fB24 = new javax.swing.JLabel();
        fB25 = new javax.swing.JLabel();
        fB26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        tfBot3 = new javax.swing.JTextField();
        fB37 = new javax.swing.JLabel();
        fB31 = new javax.swing.JLabel();
        fB32 = new javax.swing.JLabel();
        fB33 = new javax.swing.JLabel();
        fB34 = new javax.swing.JLabel();
        fB35 = new javax.swing.JLabel();
        fB36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        panelTauler = new javax.swing.JPanel();
        btnJugar = new javax.swing.JButton();
        btnPasar = new javax.swing.JButton();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        inicioOption = new javax.swing.JMenu();
        confOption = new javax.swing.JMenu();
        numJugOption = new javax.swing.JMenuItem();
        typeOption = new javax.swing.JMenuItem();
        salirOption = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel5.setLayout(null);

        tfUser.setEditable(false);
        tfUser.setText("USER");
        jPanel5.add(tfUser);
        tfUser.setBounds(10, 10, 50, 20);
        jPanel5.add(fU7);
        fU7.setBounds(10, 220, 50, 30);
        jPanel5.add(fU1);
        fU1.setBounds(10, 40, 50, 30);
        jPanel5.add(fU2);
        fU2.setBounds(10, 70, 50, 30);
        jPanel5.add(fU3);
        fU3.setBounds(10, 100, 50, 30);
        jPanel5.add(fU4);
        fU4.setBounds(10, 130, 50, 30);
        jPanel5.add(fU5);
        fU5.setBounds(10, 160, 50, 30);
        jPanel5.add(fU6);
        fU6.setBounds(10, 190, 50, 30);
        jPanel5.add(jLabel6);
        jLabel6.setBounds(0, 0, 1940, 1190);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 150, 270);

        jPanel7.setLayout(null);

        jPanel8.setLayout(null);

        tfBot1.setEditable(false);
        tfBot1.setText("BOT1");
        jPanel8.add(tfBot1);
        tfBot1.setBounds(10, 10, 50, 20);

        fB17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/domino/assets/usuario/trasera.png"))); // NOI18N
        jPanel8.add(fB17);
        fB17.setBounds(10, 220, 50, 30);

        fB11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/domino/assets/usuario/trasera.png"))); // NOI18N
        jPanel8.add(fB11);
        fB11.setBounds(10, 40, 50, 30);

        fB12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/domino/assets/usuario/trasera.png"))); // NOI18N
        jPanel8.add(fB12);
        fB12.setBounds(10, 70, 50, 30);

        fB13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/domino/assets/usuario/trasera.png"))); // NOI18N
        jPanel8.add(fB13);
        fB13.setBounds(10, 100, 50, 30);

        fB14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/domino/assets/usuario/trasera.png"))); // NOI18N
        jPanel8.add(fB14);
        fB14.setBounds(10, 130, 50, 30);

        fB15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/domino/assets/usuario/trasera.png"))); // NOI18N
        jPanel8.add(fB15);
        fB15.setBounds(10, 160, 50, 30);

        fB16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/domino/assets/usuario/trasera.png"))); // NOI18N
        jPanel8.add(fB16);
        fB16.setBounds(10, 190, 50, 30);
        jPanel8.add(jLabel21);
        jLabel21.setBounds(0, 0, 1940, 1190);

        jPanel7.add(jPanel8);
        jPanel8.setBounds(0, 0, 150, 270);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 270, 150, 250);

        jPanel9.setLayout(null);

        tfBot2.setEditable(false);
        tfBot2.setText("BOT2");
        jPanel9.add(tfBot2);
        tfBot2.setBounds(10, 10, 50, 20);

        fB27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/domino/assets/usuario/trasera.png"))); // NOI18N
        jPanel9.add(fB27);
        fB27.setBounds(10, 220, 50, 30);

        fB21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/domino/assets/usuario/trasera.png"))); // NOI18N
        jPanel9.add(fB21);
        fB21.setBounds(10, 40, 50, 30);

        fB22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/domino/assets/usuario/trasera.png"))); // NOI18N
        jPanel9.add(fB22);
        fB22.setBounds(10, 70, 50, 30);

        fB23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/domino/assets/usuario/trasera.png"))); // NOI18N
        jPanel9.add(fB23);
        fB23.setBounds(10, 100, 50, 30);

        fB24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/domino/assets/usuario/trasera.png"))); // NOI18N
        jPanel9.add(fB24);
        fB24.setBounds(10, 130, 50, 30);

        fB25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/domino/assets/usuario/trasera.png"))); // NOI18N
        jPanel9.add(fB25);
        fB25.setBounds(10, 160, 50, 30);

        fB26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/domino/assets/usuario/trasera.png"))); // NOI18N
        jPanel9.add(fB26);
        fB26.setBounds(10, 190, 50, 30);
        jPanel9.add(jLabel29);
        jLabel29.setBounds(0, 0, 1940, 1190);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(1090, 0, 150, 250);

        jPanel10.setLayout(null);

        tfBot3.setEditable(false);
        tfBot3.setText("BOT3");
        jPanel10.add(tfBot3);
        tfBot3.setBounds(10, 10, 50, 20);

        fB37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/domino/assets/usuario/trasera.png"))); // NOI18N
        jPanel10.add(fB37);
        fB37.setBounds(10, 220, 50, 30);

        fB31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/domino/assets/usuario/trasera.png"))); // NOI18N
        jPanel10.add(fB31);
        fB31.setBounds(10, 40, 50, 30);

        fB32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/domino/assets/usuario/trasera.png"))); // NOI18N
        jPanel10.add(fB32);
        fB32.setBounds(10, 70, 50, 30);

        fB33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/domino/assets/usuario/trasera.png"))); // NOI18N
        jPanel10.add(fB33);
        fB33.setBounds(10, 100, 50, 30);

        fB34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/domino/assets/usuario/trasera.png"))); // NOI18N
        jPanel10.add(fB34);
        fB34.setBounds(10, 130, 50, 30);

        fB35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/domino/assets/usuario/trasera.png"))); // NOI18N
        jPanel10.add(fB35);
        fB35.setBounds(10, 160, 50, 30);

        fB36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/domino/assets/usuario/trasera.png"))); // NOI18N
        jPanel10.add(fB36);
        fB36.setBounds(10, 190, 50, 30);
        jPanel10.add(jLabel37);
        jLabel37.setBounds(0, 0, 1940, 1190);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(1090, 250, 150, 270);

        panelTauler.setBackground(new java.awt.Color(204, 255, 204));

        btnJugar.setText("Jugar");
        btnJugar.setEnabled(false);

        btnPasar.setText("Pasar");
        btnPasar.setEnabled(false);

        img1.setMaximumSize(new java.awt.Dimension(25, 50));
        img1.setMinimumSize(new java.awt.Dimension(25, 50));
        img1.setPreferredSize(new java.awt.Dimension(25, 50));
        img1.setRequestFocusEnabled(false);

        img2.setMaximumSize(new java.awt.Dimension(25, 50));
        img2.setMinimumSize(new java.awt.Dimension(25, 50));
        img2.setPreferredSize(new java.awt.Dimension(25, 50));
        img2.setRequestFocusEnabled(false);

        img3.setMaximumSize(new java.awt.Dimension(25, 50));
        img3.setMinimumSize(new java.awt.Dimension(25, 50));
        img3.setPreferredSize(new java.awt.Dimension(25, 50));
        img3.setRequestFocusEnabled(false);

        javax.swing.GroupLayout panelTaulerLayout = new javax.swing.GroupLayout(panelTauler);
        panelTauler.setLayout(panelTaulerLayout);
        panelTaulerLayout.setHorizontalGroup(
            panelTaulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTaulerLayout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(btnPasar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169)
                .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(307, 307, 307))
            .addGroup(panelTaulerLayout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(img2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(img3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTaulerLayout.setVerticalGroup(
            panelTaulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTaulerLayout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addGroup(panelTaulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(154, 154, 154)
                .addGroup(panelTaulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJugar)
                    .addComponent(btnPasar))
                .addContainerGap())
        );

        getContentPane().add(panelTauler);
        panelTauler.setBounds(150, 0, 940, 520);

        inicioOption.setText("Inicio");
        menuBar.add(inicioOption);

        confOption.setText("Configuracion");

        numJugOption.setText("Numero de jugadors");
        confOption.add(numJugOption);

        typeOption.setText("Tipus de partida");
        confOption.add(typeOption);

        menuBar.add(confOption);

        salirOption.setText("Salir");
        menuBar.add(salirOption);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnPasar;
    private javax.swing.JMenu confOption;
    private javax.swing.JLabel fB11;
    private javax.swing.JLabel fB12;
    private javax.swing.JLabel fB13;
    private javax.swing.JLabel fB14;
    private javax.swing.JLabel fB15;
    private javax.swing.JLabel fB16;
    private javax.swing.JLabel fB17;
    private javax.swing.JLabel fB21;
    private javax.swing.JLabel fB22;
    private javax.swing.JLabel fB23;
    private javax.swing.JLabel fB24;
    private javax.swing.JLabel fB25;
    private javax.swing.JLabel fB26;
    private javax.swing.JLabel fB27;
    private javax.swing.JLabel fB31;
    private javax.swing.JLabel fB32;
    private javax.swing.JLabel fB33;
    private javax.swing.JLabel fB34;
    private javax.swing.JLabel fB35;
    private javax.swing.JLabel fB36;
    private javax.swing.JLabel fB37;
    private javax.swing.JLabel fU1;
    private javax.swing.JLabel fU2;
    private javax.swing.JLabel fU3;
    private javax.swing.JLabel fU4;
    private javax.swing.JLabel fU5;
    private javax.swing.JLabel fU6;
    private javax.swing.JLabel fU7;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JMenu inicioOption;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem numJugOption;
    private javax.swing.JPanel panelTauler;
    private javax.swing.JMenu salirOption;
    private javax.swing.JTextField tfBot1;
    private javax.swing.JTextField tfBot2;
    private javax.swing.JTextField tfBot3;
    private javax.swing.JTextField tfUser;
    private javax.swing.JMenuItem typeOption;
    // End of variables declaration//GEN-END:variables

    public String[] getNomJugs() {
        return nomJugs;
    }

    public void setNomJugs(String[] nomJugs) {
        this.nomJugs = nomJugs;
    }

}
